---
kind: pipeline
type: docker
name: default

steps:
  - name: Build & Test
    image: rust:latest
    commands:
      - sudo apt-get install -y libdbus-1-dev
      - cargo build --release
  - name: publish
    image: plugins/gitea-release
    settings:
      api_key: 
        from_secret: gitea_token

      base_url: https://git.uttarayan.me
      files: target/release/mctl
      checksum:
        - md5
        - sha1
        - sha256
        - sha512
    when:
      event: tag
