---
kind: pipeline
type: docker
name: default

steps:
  - name: Build & Package
    image: rust:latest
    commands:
      - apt-get update
      - apt-get install -y libdbus-1-dev
      - cargo build --release
      - tar -czvf mctl-${DRONE_TAG}-linux.tar.gz README.md -C target/release mctl
  - name: publish
    image: plugins/gitea-release
    settings:
      api_key: 
        from_secret: gitea_token

      base_url: https://git.uttarayan.me
      files: mctl-${DRONE_TAG}-linux.tar.gz
      checksum:
        - sha256
    when:
      event: tag
