# Maintainer: Uttarayan Mondal <uttarayan21@gmail.com>
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=mctl-bin
pkgver=0.1.0
pkgrel=1
pkgdesc="Control both mpd and mpris musicplayers with one command"
url="https://github.com/uttarayan21/mctl-rs"
license=("LICENSE")
arch=("x86_64")
provides=("mctl")
conflicts=("mctl")
source=("https://github.com/uttarayan21/mctl-rs/releases/download/v$pkgver/mctl-$pkgver-x86_64.tar.gz")
sha256sums=("238350d5869c5ad77a7a0f9c1b9edb3f82ab115685a7a6a771a8b8f666883e29")

package() {
    install -Dm755 mctl -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
