# Maintainer: Uttarayan Mondal <uttarayan21@gmail.com>
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=mctl-bin
pkgver=0.1.0
pkgrel=1
pkgdesc="Control both mpd and mpris musicplayers with one command"
url="https://github.com/uttarayan21/mctl-rs"
license=("LICENSE")
arch=("x86_64")
provides=("mctl")
conflicts=("mctl")
source=("https://github.com/uttarayan21/mctl-rs/releases/download/v$pkgver/mctl-$pkgver-x86_64.tar.gz")
sha256sums=("b1be836a9506dc88638d1a899ddc3d2b29335def97a041a3595de3c5e6517b26")

package() {
    install -Dm755 mctl -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
