# Maintainer: Uttarayan Mondal <uttarayan21@gmail.com>
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=mctl-bin
pkgver=0.1.0
pkgrel=1
pkgdesc="Control both mpd and mpris musicplayers with one command"
url="https://github.com/uttarayan21/mctl-rs"
license=("LICENSE")
arch=("x86_64")
provides=("mctl")
conflicts=("mctl")
source=("https://github.com/uttarayan21/mctl-rs/releases/download/v$pkgver/mctl-$pkgver-x86_64.tar.gz")
sha256sums=("9a837db16fb6dca4ba64613978c3b0ec12cd7f2d9483445d9766b33d24de860b")

package() {
    install -Dm755 mctl -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
