name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dbus
      run: sudo apt-get install -y libdbus-1-dev pkg-config

    - name: Run tests
      run: cargo test --verbose

    - name: Build
      run: cargo build --verbose --release

    - name: Strip
      run: strip target/release/mctl

    - name: Compress
      run: tar -czvf mctl-${GITHUB_REF#refs/*/}-linux.tar.gz README.md LICENSE -C target/release mctl
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          mctl-${GITHUB_REF#refs/*/}-linux.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



